const data = {
  "atlantis": [
    "Atlantis Archer",
    "Atlantis Archery",
    "Atlantis Decoration",
    "Atlantis Field",
    "Atlantis Mill",
    "Atlantis Quarters",
    "Atlantis Tower",
    "Atlantis Wall",
    "Atlantis Warrior",
    "Crab Knight",
    "Crab Stables",
    "Neptune's Palace",
    "Neptune",
    "Poseidon Barracks",
    "Poseidon",
    "Seahorse Stables",
    "Seahorse",
    "Water Tower"
  ],
  "aztec": [
    "Aztec Ball Field",
    "Aztec Boss",
    "Aztec Calendar",
    "Aztec Decoration",
    "Aztec Field",
    "Aztec House",
    "Aztec Isle",
    "Aztec Lamb",
    "Aztec Mill",
    "Aztec Quarters",
    "Aztec Temple",
    "Aztec Tower",
    "Aztec Wall",
    "Aztec Warrior"
  ],
  "celestial": [
    "Avenging Paladin Barracks",
    "Avenging Paladin",
    "Celestial Archer",
    "Celestial Archery",
    "Celestial Barracks",
    "Celestial Cloud",
    "Celestial Draggy",
    "Celestial Field",
    "Celestial Garden",
    "Celestial Gryphon Barracks",
    "Celestial House",
    "Celestial Lancer Barracks",
    "Celestial Lancer",
    "Celestial Mech",
    "Celestial Mecha Barracks",
    "Celestial Mill",
    "Celestial Priest",
    "Celestial Reaper Barracks",
    "Celestial Reaper",
    "Celestial Shrine",
    "Celestial Soldier",
    "Celestial Statue",
    "Celestial Supreme Barracks",
    "Celestial Supreme",
    "Celestial Tower",
    "Celestial Wall",
    "Gryphon Knight",
    "Punisher Knight Barrack",
    "Punisher Knight",
    "Rider Academy"
  ],
  "china": [
    "Bamboo Mill",
    "Chinese Archer",
    "Chinese Archery",
    "Chinese Festival",
    "Chinese Field",
    "Chinese House",
    "Chinese Isle",
    "Chinese Temple",
    "Chinese Tower",
    "Chinese Tree1",
    "Chinese Tree2",
    "Chinese Wall1",
    "Chinese Wall2"
  ],
  "egypt": [
    "Anubis Avatar",
    "Anubis God Barracks",
    "Anubis God",
    "Anubis Statue1",
    "Anubis Statue2",
    "Anubis Temple",
    "Black Anubis",
    "Camel Rider",
    "Camel Stables",
    "Camel",
    "Cat Statue",
    "Cleopatra",
    "Cobra Rider Barracks",
    "Cobra Rider",
    "Colossal Cobra",
    "Egyptian Altar",
    "Egyptian Field",
    "Egyptian House",
    "Egyptian Isle",
    "Egyptian Mine",
    "Egyptian Quarters",
    "Egyptian Tower",
    "Egyptian Wall",
    "Egyptian Warrior",
    "Evil Anubis Warrior",
    "Goat Sphinx",
    "Guardian Archer Barracks",
    "Guardian Archer",
    "Guardian Axe Barracks",
    "Guardian Axe",
    "Guardian Swordsman Barracks",
    "Guardian Swordsman",
    "Horus Gryphon Barracks",
    "Horus Gryphon",
    "Horus Herald Barracks",
    "Horus Herald",
    "Isis Healer Barracks",
    "Isis Healer",
    "Isis Statue",
    "Keops Pyramid",
    "Mask",
    "Medium Pyramid",
    "Mini Anubis",
    "Mummy Pyramid",
    "Mummy",
    "Pharaoh's Field",
    "Pharaoh's House",
    "Pharaoh's Tower",
    "Pharaoh's Wall",
    "Pharaoh",
    "Pharoah's Gold Mine",
    "Power Gem",
    "Pyramid",
    "Ra Sphinx",
    "Ra Statue",
    "Ramses II Barracks",
    "Ramses II",
    "Sarcophagus1",
    "Sarcophagus2",
    "Scarab Rider Barracks",
    "Scarab Rider",
    "Small Pyramid",
    "Sphinx Barracks",
    "Tuthankamon Barracks",
    "Tuthankamon"
  ],
  "elf": [
    "Druid's Council",
    "Druid's Hut",
    "Elf Archer Barracks",
    "Elf Archer",
    "Elf Archery",
    "Elf Axe Barracks",
    "Elf Balista",
    "Elf Barracks",
    "Elf Catapult Barracks",
    "Elf Druid",
    "Elf Eagle Aviary",
    "Elf Field",
    "Elf Fountain",
    "Elf Gazebo",
    "Elf Gryphon Barracks",
    "Elf Hero Statue",
    "Elf House",
    "Elf Knight Barracks",
    "Elf Life Tree",
    "Elf Mill",
    "Elf Priest Barracks",
    "Elf Priest",
    "Elf Reptile Barracks",
    "Elf Reptile Statue",
    "Elf Royal Archer",
    "Elf Stables",
    "Elf Swordsman Barracks",
    "Elf Tiger",
    "Elf Tower",
    "Elf Wall",
    "Elf Warior",
    "Elf Workshop",
    "High Elf (not in unit list)",
    "High Elf",
    "Imperial Elf Archer",
    "Imperial Elf Axe",
    "Imperial Elf Catapult",
    "Imperial Elf Field",
    "Imperial Elf Fountain",
    "Imperial Elf Gryphon",
    "Imperial Elf House",
    "Imperial Elf Knight",
    "Imperial Elf Mill",
    "Imperial Elf Sword",
    "Imperial Elf Tower",
    "Imperial Elf Wall",
    "Royal Archery",
    "Royal Barracks",
    "Royal Elf"
  ],
  "gladiator": [
    "4-Weapons Gladiator Barracks",
    "4-Weapons Gladiator",
    "Blade Gladiator Barracks",
    "Blade Gladiator",
    "Bull Gladiator Barracks",
    "Bull Gladiator",
    "Caesar Gladiator Barracks",
    "Caesar Gladiator",
    "Centaur Gladiator Barracks",
    "Centaur Gladiator",
    "Chariot Gladiator Barracks",
    "Chariot Gladiator",
    "Demolisher Gladiator Barracks",
    "Demolisher Gladiator",
    "Devil Gladiator Barracks",
    "Devil Gladiator",
    "Gladiator Field",
    "Gladiator House",
    "Gladiator Mill",
    "Gladiator Tower",
    "Gladiator Wall",
    "Golden Gladiator Statue",
    "Knight Gladiator Barracks",
    "Knight Gladiator",
    "Lion Soul Gladiator Barracks",
    "Lion Soul Gladiator",
    "Lizard Gladiator Barracks",
    "Lizard Gladiator",
    "Mace Gladiator Barracks",
    "Mace Gladiator",
    "Minotaur Gladiator Barracks",
    "Minotaur Gladiator",
    "Priest Gladiator Barracks",
    "Priest Gladiator",
    "Spearman Gladiator Barracks",
    "Spearman Gladiator",
    "Sword Gladiator Barraks",
    "Sword Gladiator"
  ],
  "haunted": [
    "Black Witch Barracks",
    "Black Witch",
    "Evil Pumpkin Monster",
    "Frankenstein Barracks",
    "Frankenstein",
    "Graveyard",
    "Grim Reaper",
    "Halloween Field",
    "Halloween House",
    "Halloween Mill",
    "Halloween Super Tower",
    "Halloween Tower",
    "Halloween Wall",
    "Haunted House",
    "Mr. Bones Barrack",
    "Mr. Bones",
    "Pumpkin Monster",
    "Scary Zombie Barracks",
    "Werewolf Barrack"
  ],
  "home": [
    "Abandoned Mine",
    "Academy",
    "Allies Market",
    "Archery I",
    "Archery II",
    "Archery III",
    "Archery IV",
    "Archery Stables",
    "Archery V",
    "Bakery",
    "Barrack V",
    "Barracks I",
    "Barracks II",
    "Barracks III",
    "Barracks IV",
    "Blacksmith",
    "Boy Villager",
    "Burning Mill",
    "Cow Ranch I",
    "Cow Ranch II",
    "Cow Ranch III",
    "Cow",
    "Crying Cow",
    "Crying Sheep",
    "Eagle IV",
    "Eagle",
    "Eagles I",
    "Eagles II",
    "Eagles III",
    "Elephant Rider",
    "Elephant Stables",
    "Engineer Barrack",
    "Engineer",
    "Forestry Academy",
    "Girl Villager",
    "Gold Mine I",
    "Gold Mine II",
    "Gold Mine III",
    "Gold Mine IV",
    "Heavy Archer Knight",
    "Heavy Archer",
    "Heavy Knight",
    "Horse Stable",
    "House I",
    "House II",
    "House III",
    "House IV",
    "House V",
    "Light Archer Knight",
    "Light Archer",
    "Light Knight",
    "Lost Soldier",
    "Lumber Mill IV",
    "Market II",
    "Market III",
    "Market",
    "Medium Archer Knight",
    "Medium Archer",
    "Medium Knight",
    "Medium Swordsman",
    "Mill I",
    "Mill II",
    "Mill III",
    "Mill IV",
    "Mine Academy",
    "Mobile Tower",
    "Powerful Archer Knight",
    "Powerful Archer",
    "Powerful Knight",
    "Powerful Swordman",
    "Prisoner Archers",
    "Restaurant",
    "Royal Archer Knight",
    "Royal Archer",
    "Royal Knight",
    "Sheep Ranch I",
    "Sheep Ranch II",
    "Sheep Ranch III",
    "Sheep",
    "Spearman",
    "Spell Academy",
    "Stables II",
    "Stables III",
    "Stables IV",
    "Stables V",
    "Stables",
    "Stone Mine I",
    "Stone Mine II",
    "Stone Mine III",
    "Stone Mine IV",
    "Tower I",
    "Tower II",
    "Tower III",
    "Tower IV",
    "Tower V",
    "Tower Workshop",
    "Town Hall I",
    "Town Hall II",
    "Town Hall III",
    "Town Hall IV",
    "Trapped Villager",
    "Treasure Burning Mill",
    "Wall Door",
    "Wall I",
    "Wall II",
    "Wall III",
    "Wall IV",
    "Wall V",
    "Warrior Princess",
    "Willy Wallace",
    "Wood Mine I",
    "Wood Mine II",
    "Wood Mine III",
    "Workshop I",
    "Workshop II",
    "Workshop III",
    "Workshop IV"
  ],
  "inferno": [
    "Demon Crusher",
    "Demonic Statue",
    "Infernal Archer",
    "Infernal Archery",
    "Infernal Barrack",
    "Infernal Demon",
    "Infernal Dragon Rider",
    "Infernal Dragon",
    "Infernal Field",
    "Infernal Halberdier",
    "Infernal Halberdiery",
    "Infernal Headquarters",
    "Infernal Kamikaze Center",
    "Infernal Kamikaze",
    "Infernal Knight",
    "Infernal Minion",
    "Infernal Portal",
    "Infernal Quarters",
    "Infernal Rhino Rider",
    "Infernal Rider",
    "Infernal Sculpture",
    "Infernal Stables",
    "Infernal Tower",
    "Infernal Wall",
    "Infernal Warrior"
  ],
  "mythological": [
    "Ancient Ruins",
    "God Zeus",
    "Hercules Barracks",
    "Hercules Statue",
    "Hermes Barracks",
    "Hermes Spearman Barracks",
    "Hermes Spearman",
    "Hermes Swordsman Barracks",
    "Hermes Swordsman",
    "Hermes",
    "Icarus Barracks",
    "Icarus",
    "Myth Field",
    "Myth House",
    "Myth Mill",
    "Myth Statue",
    "Myth Tower",
    "Myth Wall",
    "Stratos Barracks",
    "Stratos Titan",
    "Zeus Barracks"
  ],
  "necro": [
    "Axe Skeleton Barracks",
    "Axe Skeleton",
    "Beholder Eye",
    "Death Draggy",
    "Death Dragon Rider",
    "Death Dragon",
    "Draco Fountain",
    "Evil Scorpion",
    "Green Emerald1",
    "Necro Abomination",
    "Necro Archer Barracks",
    "Necro Archer",
    "Necro Dark Lord Barracks",
    "Necro Dark Lord",
    "Necro Double Sword Barracks",
    "Necro Double Swordsman",
    "Necro Field",
    "Necro Fork Barracks",
    "Necro Fork Soldier",
    "Necro Ghost Barracks",
    "Necro Ghost",
    "Necro Gryphon Knight",
    "Necro Harvester Barracks",
    "Necro Harvester",
    "Necro Horseman Barracks",
    "Necro Horseman",
    "Necro House",
    "Necro King Barracks",
    "Necro King",
    "Necro Mill",
    "Necro Mulitarms Barracks",
    "Necro Multiarms",
    "Necro Paladin Barracks",
    "Necro Paladin",
    "Necro Priest Castle",
    "Necro Priest",
    "Necro Rhino Barracks",
    "Necro Rhino",
    "Necro Shark",
    "Necro Tower",
    "Necro Wall",
    "Necro Warrior Barracks",
    "Necro Warrior",
    "Necro Winged Barracks",
    "Necro Winged Warrior",
    "Necro Worm",
    "Skeleton Archer Barracks",
    "Skeleton Archer",
    "Sword Skeleton Barracks",
    "Sword Skeleton"
  ],
  "orc": [
    "2-Head Orc",
    "Big Basher Orc Barracks",
    "Big Basher Orc",
    "Boomerang Orc Barracks",
    "Boomerang Orc",
    "Crusher Orc Barracks",
    "Crusher Orc",
    "Dark Orc Field",
    "Dark Orc House",
    "Dark Orc Mill",
    "Dark Orc Tower",
    "Dark Orc Wall",
    "Dark Orcs Banner",
    "Dual Axe Orc Barracks",
    "Dual Axe Orc",
    "Evil Orc Dragon",
    "Orc Battering Ram Barracks",
    "Orc Battering Ram",
    "Orc Dragon",
    "Orc Spear Warrior Barracks",
    "Orc Spear Warrior",
    "Priest Orc Barracks",
    "Priest Orc",
    "Spider Orc Rider Barracks",
    "Spider Orc Rider",
    "TNT Orc Barracks",
    "TNT Orc",
    "Torch"
  ],
  "troll": [
    "Axe Thrower",
    "Barracks Boulder",
    "Battle Troll",
    "Big Troll",
    "Boar Rider",
    "Brute Knight",
    "Brute Swordsman",
    "Chained Troll",
    "Devious Troll",
    "Injured Troll",
    "Nice Troll",
    "Rehabbed Troll",
    "Reveger Troll",
    "Revenger Troll",
    "Small Troll",
    "Troll Allies Market",
    "Troll Archer",
    "Troll Archery I",
    "Troll Archery II",
    "Troll Barracks I",
    "Troll Barracks II",
    "Troll Barracks III",
    "Troll Barracks IV",
    "Troll Barracks V",
    "Troll Barracks VI",
    "Troll Bathroom",
    "Troll Boar Ranch I",
    "Troll Boar Ranch II",
    "Troll Boar Ranch III",
    "Troll Boar Stables",
    "Troll Canon",
    "Troll Castle I",
    "Troll Castle II",
    "Troll Catapult",
    "Troll Cave",
    "Troll Coliseum",
    "Troll Eagles I",
    "Troll Eagles II",
    "Troll Eagles III",
    "Troll Field II",
    "Troll Field III",
    "Troll Field",
    "Troll Fist",
    "Troll Gold Mine I",
    "Troll Gold Mine II",
    "Troll Gold Mine III",
    "Troll Hall I",
    "Troll Hall II",
    "Troll Hall III",
    "Troll Hand",
    "Troll Harbour",
    "Troll House I",
    "Troll House II",
    "Troll House III",
    "Troll Hut",
    "Troll Lumber Mill I",
    "Troll Lumber Mill II",
    "Troll Lumber Mill III",
    "Troll Market I",
    "Troll Market II",
    "Troll Market III",
    "Troll Mill I",
    "Troll Mill II",
    "Troll Mill III",
    "Troll Ram",
    "Troll Rhino Rider",
    "Troll Scorpion",
    "Troll Statue",
    "Troll Stone Mill III",
    "Troll Stone Mine I",
    "Troll Stone Mine II",
    "Troll Tower I",
    "Troll Tower II",
    "Troll Tower III",
    "Troll Tower IV",
    "Troll Tower V",
    "Troll Villager (Boy)",
    "Troll Villager (Girl)",
    "Troll Wall I",
    "Troll Wall II",
    "Troll Wall III",
    "Troll Workshop I",
    "Troll Workshop II",
    "Troll Workshop III",
    "Troll Workshop IV",
    "Troll Zeppelin",
    "Troll's Allies Building",
    "Voodoo Healer",
    "War Troll"
  ],
  "viking": [
    "Axe Viking",
    "Viking Axe Quarters",
    "Viking Festival",
    "Viking Field",
    "Viking Mine",
    "Viking Mistress",
    "Viking Quarters",
    "Viking Ship1",
    "Viking Ship2",
    "Viking Statue1",
    "Viking Statue2",
    "Viking Statue3",
    "Viking Tower",
    "Viking Wall",
    "Viking"
  ]
}

export default data
